import { deflateRawSync } from "zlib";
import {
  parseZip,
  ZipParseError,
  MAX_ZIP_ENTRY_BYTES,
  MAX_ZIP_ENTRIES,
} from "./zip.util";

// ---------------------------------------------------------------------------
// Small test ZIP writer. Produces archives with sizes written in the local
// file header (no data descriptors), matching how standard tools write to a
// seekable file.
// ---------------------------------------------------------------------------
interface ZipItem {
  name: string;
  content: Buffer;
  method?: 0 | 8;
  flags?: number;
}

function writeLocalHeader(
  chunks: Buffer[],
  item: ZipItem,
  compressed: Buffer,
): void {
  const header = Buffer.alloc(30);
  header.writeUInt32LE(0x04034b50, 0); // PK\x03\x04
  header.writeUInt16LE(20, 4); // version needed
  header.writeUInt16LE(item.flags ?? 0, 6);
  header.writeUInt16LE(item.method ?? 0, 8);
  header.writeUInt16LE(0, 10); // mod time
  header.writeUInt16LE(0, 12); // mod date
  header.writeUInt32LE(0, 14); // crc32 (unchecked by parser)
  header.writeUInt32LE(compressed.length, 18);
  header.writeUInt32LE(item.content.length, 22);
  header.writeUInt16LE(Buffer.byteLength(item.name), 26);
  header.writeUInt16LE(0, 28); // extra length
  chunks.push(header);
  chunks.push(Buffer.from(item.name));
  chunks.push(compressed);
}

function makeZip(items: ZipItem[]): Buffer {
  const chunks: Buffer[] = [];
  for (const item of items) {
    const method = item.method ?? 0;
    const compressed =
      method === 8 ? deflateRawSync(item.content) : item.content;
    writeLocalHeader(chunks, item, compressed);
  }
  // End-of-central-directory record (parser stops at it).
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  chunks.push(eocd);
  return Buffer.concat(chunks);
}

const SAMPLE_JSON = JSON.stringify([
  { title: "From Zip", description: "d", code: "x", language: "javascript", tags: ["z"] },
]);

// Independent oracle: a ZIP generated with Python's zipfile (deflate).
const PYTHON_ZIP_BASE64 =
  "UEsDBBQAAAAIAMttGl2fVX1RbQAAAIMAAAANAAAAc25pcHBldHMuanNvbiXMsQoCQQwE0F8JqRREsPUDBGs7jyvCblgie5uwGy1O/HfN2c6bmemNLl4Zz4DXxbQ7Z7iLwa2JGTseADOP1MVctEXt0nWBVSwoad6mSdvQyseqZXfah1Rq5Ull0we96H8R4lTGL50wPubP/AVQSwECFAMUAAAACADLbRpdn1V9UW0AAACDAAAADQAAAAAAAAAAAAAAgAEAAAAAc25pcHBldHMuanNvblBLBQYAAAAAAQABADsAAACYAAAAAAA=";

describe("parseZip", () => {
  it("parses a stored (uncompressed) ZIP", () => {
    const zip = makeZip([{ name: "snippets.json", content: Buffer.from(SAMPLE_JSON) }]);
    const entries = parseZip(zip);
    expect(entries).toHaveLength(1);
    expect(entries[0].filename).toBe("snippets.json");
    expect(entries[0].content).toBe(SAMPLE_JSON);
  });

  it("parses a deflate-compressed ZIP", () => {
    const zip = makeZip([{ name: "snippets.json", content: Buffer.from(SAMPLE_JSON), method: 8 }]);
    const entries = parseZip(zip);
    expect(entries).toHaveLength(1);
    expect(entries[0].content).toBe(SAMPLE_JSON);
  });

  it("parses a ZIP generated by an external tool (Python zipfile)", () => {
    const entries = parseZip(Buffer.from(PYTHON_ZIP_BASE64, "base64"));
    expect(entries).toHaveLength(1);
    expect(entries[0].filename).toBe("snippets.json");
    const parsed = JSON.parse(entries[0].content);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed[0].title).toBe("Imported Zip Snippet");
  });

  it("skips directory entries", () => {
    const zip = makeZip([
      { name: "folder/", content: Buffer.alloc(0) },
      { name: "snippets.json", content: Buffer.from(SAMPLE_JSON) },
    ]);
    const entries = parseZip(zip);
    expect(entries).toHaveLength(1);
    expect(entries[0].filename).toBe("snippets.json");
  });

  it("parses multiple file entries", () => {
    const zip = makeZip([
      { name: "a.json", content: Buffer.from("{}") },
      { name: "b.json", content: Buffer.from("[]"), method: 8 },
    ]);
    const entries = parseZip(zip);
    expect(entries.map((e) => e.filename)).toEqual(["a.json", "b.json"]);
  });

  it("rejects a buffer that is not a ZIP", () => {
    expect(() => parseZip(Buffer.from("this is not a zip file"))).toThrow(ZipParseError);
  });

  it("rejects an empty buffer", () => {
    expect(() => parseZip(Buffer.alloc(0))).toThrow(ZipParseError);
  });

  it("rejects a truncated ZIP", () => {
    const zip = makeZip([{ name: "snippets.json", content: Buffer.from(SAMPLE_JSON), method: 8 }]);
    // Cut off mid-entry so the entry data is incomplete.
    expect(() => parseZip(zip.subarray(0, 40))).toThrow(ZipParseError);
  });

  it("rejects entries using unsupported compression methods", () => {
    const zip = makeZip([{ name: "snippets.json", content: Buffer.from("{}") }]);
    // Corrupt the compression-method field of the local header.
    zip.writeUInt16LE(99, 8);
    expect(() => parseZip(zip)).toThrow(ZipParseError);
  });

  it("rejects streamed entries (data descriptor flag set)", () => {
    const zip = makeZip([
      { name: "snippets.json", content: Buffer.from("{}"), flags: 0x08 },
    ]);
    expect(() => parseZip(zip)).toThrow(ZipParseError);
  });

  it("rejects a ZIP bomb that decompresses beyond the entry limit", () => {
    const bomb = Buffer.alloc(MAX_ZIP_ENTRY_BYTES + 1024, 65);
    const zip = makeZip([{ name: "huge.json", content: bomb, method: 8 }]);
    expect(() => parseZip(zip)).toThrow(ZipParseError);
  });

  it("rejects archives with too many entries", () => {
    const items: ZipItem[] = [];
    for (let i = 0; i <= MAX_ZIP_ENTRIES; i++) {
      items.push({ name: `file-${i}.json`, content: Buffer.from("{}") });
    }
    const zip = makeZip(items);
    expect(() => parseZip(zip)).toThrow(ZipParseError);
  });

  it("rejects archives with no file entries", () => {
    // Only an end-of-central-directory record.
    const eocd = Buffer.alloc(22);
    eocd.writeUInt32LE(0x06054b50, 0);
    expect(() => parseZip(eocd)).toThrow(/contains no file entries/);
  });
});
